### ISSUE TITLE
Webpack - wait until bundle finished

### ISSUE THREAD

**Issue by glittle** [oliviertassinari/serviceworker-webpack-plugin#16]
After adding the plugin config to the webpack config file (see https://github.com/glittle/badi-web3/blob/master/build/webpack.dev.conf.js), when I start the system, it stalls forever and says:

    webpack: wait until bundle finished: /__webpack_hmr

If I remove lines 37-39 of that file, it works fine.  The file referenced in the `entry` exists.

What am I missing?

**Comment by glittle** [comment]
Thanks, Olivier.  

    new serviceWorkerPlugin({
    ^
    TypeError: serviceWorkerPlugin is not a constructor

With the `.default` added, I get the above error.  And removing the `new` doesn't help, of course.

In reviewing what I'm doing, what I really want is simply the ability to specify a file that will be served from the root of the website beside the 'index.js', both in the `dev` environment and when the `build` is run.  Do you have any suggestions on how I can do that? It seems that this is a webpack configuration exercise, but I haven't found how to do it.

**Comment by oliviertassinari** [comment]
My bad, we already have the `add-module-exports` babel plugin. No need for that `.default`.

**Comment by oliviertassinari** [comment]
I'm gonna close that issue. Sorry, I don't have time to investigate.

**Comment by rstoenescu** [comment]
Hi,

I think best would be to at least leave it open for when you'll have time for it. I know how time can be an issue in itself, but this does needs a fix.

Great work with the plugin btw.

**Comment by glittle** [comment]
I've changed my approach so that I no longer need this plugin... so you don't need to hold it open on my behalf.

**Comment by oliviertassinari** [comment]
Actually, it's could be linked to an issue with webpack@2. I'm looking into that.

**Comment by oliviertassinari** [comment]
Wrong assumption, it's working fine with it: #17.

**Comment by oliviertassinari** [comment]
I have figured our the issue using https://github.com/glittle/badi-web3/commit/2201697.
Actually, there are two issues right here.

### 1. Wrong parameter

@glittle The path you are providing doesn't match with a file on the system...
```diff
-entry: path.join(__dirname, 'special/sw-badi-web3.js'),
+entry: path.join(__dirname, '../special/sw-badi-web3.js')
```

### 2. Error swallowed

@rstoenescu as the `path` argument provided is invalid, the `ServiceWorkerPlugin` plugin crash and throw an exception. However, that error is never showed. That's most likely due to the custom logic implemented inside `build/script.dev.js`. I suggest you having a look at the https://github.com/webpack/webpack-dev-server implementation could help.
