### ISSUE TITLE
It seems that your are importing "serviceworker-webpack-plugin/lib/runtime" without using the plugin. Makes sure that your webpack configuration is correct.

### ISSUE THREAD

**Issue by dshiells** [oliviertassinari/serviceworker-webpack-plugin#37]
When following the instructions I get the following error:
`Error: serviceworker-webpack-plugin: It seems that your are importing
  "serviceworker-webpack-plugin/lib/runtime" without using the plugin.
  Makes sure that your webpack configuration is correct.`

This makes sense as `serviceworker-webpack-plugin/lib/runtime` just contains an error:

> "use strict";
> 
> /* eslint-disable flowtype/require-valid-file-annotation */
> 
> throw new Error("serviceworker-webpack-plugin: It seems that your are importing\n  > \"serviceworker-webpack-plugin/lib/runtime\" without using the plugin.\n  Makes sure that your webpack configuration is correct.");

Why do we import a file that just contains an error? And what SHOULD we be doing?

Thanks.

**Comment by oliviertassinari** [comment]
> Why do we import a file that just contains an error?

This file is [hijacked](https://github.com/oliviertassinari/serviceworker-webpack-plugin/blob/eeb4b127fd5f86b6f1e1b6506433128589a2ed71/src/index.js#L56) by the plugin.
It's a simpler helper so that you only have to specify the service worker location once when configuring the webpack plugin. That's not doing much.

> And what SHOULD we be doing?

You are missing step 1. : `Add the plugin to your webpack config`.
